import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col bg-black text-white w-screen h-screen">
          <div className="h-16 fixed w-full bg-black z-10">
            <Navbar />
          </div>
          <div className="h-[calc(100vh-4rem)] mt-16">{children}</div>
        </div>
      </body>
    </html>
  );
}
